import "./globals.css";
import Nav from "./(components)/Nav";
import Footer from "./(components)/Footer";
import Provider from "./(components)/Provider";

export const metadata = {
  title: "Circle Programmable Wallets Bounty",
  description: "Generated by Nashki",
  icons: {
    icon: "icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body >
          <Provider>
            <Nav />
            {children}
            <Footer />
          </Provider>
        </body>
      </html>
  );
}
